import type { Issue, PortfolioProfile } from './types';

export const STATIC_ISSUES: Issue[] = [
  {
    id: 1,
    featured: true,
    repo: 'fastapi/fastapi',
    repoStars: '73.4k',
    repoStarsNum: 73400,
    av: 'FA',
    avColor: 'green',
    title: 'Add missing type hints to dependency injection utilities',
    desc: 'The `Depends()` utility functions are missing proper type hints in the core injection module. This is a great intro to FastAPI internals.',
    tags: [
      { label: 'Beginner', type: 'difficulty' },
      { label: 'Python', type: 'lang' },
      { label: 'Type Hints', type: 'topic' },
      { label: 'good-first-issue', type: 'topic' },
    ],
    difficulty: 'beginner',
    difficultyPct: 22,
    lang: 'python',
    comments: 4,
    age: '2 days',
    assignees: 0,
    estTime: '2–3 hours',
    githubUrl: 'https://github.com/fastapi/fastapi/issues',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    repo: 'vercel/next.js',
    repoStars: '119k',
    repoStarsNum: 119000,
    av: 'NX',
    avColor: 'dark',
    title: 'Fix misleading error message when API route returns undefined',
    desc: 'When an API route handler returns undefined instead of a Response, the error thrown is confusing. Improve the error message with a helpful hint.',
    tags: [
      { label: 'Beginner', type: 'difficulty' },
      { label: 'TypeScript', type: 'lang' },
      { label: 'Bug Fix', type: 'topic' },
      { label: 'good-first-issue', type: 'topic' },
    ],
    difficulty: 'beginner',
    difficultyPct: 18,
    lang: 'ts',
    comments: 7,
    age: '1 day',
    assignees: 0,
    estTime: '1–2 hours',
    githubUrl: 'https://github.com/vercel/next.js/issues',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    repo: 'supabase/supabase',
    repoStars: '61.2k',
    repoStarsNum: 61200,
    av: 'SB',
    avColor: 'green',
    title: 'Write unit tests for the storage bucket validation logic',
    desc: 'The bucket name validation function in `storage-js` lacks test coverage. Add a test suite using Vitest covering edge cases like special chars and length limits.',
    tags: [
      { label: 'Intermediate', type: 'difficulty' },
      { label: 'TypeScript', type: 'lang' },
      { label: 'Testing', type: 'topic' },
    ],
    difficulty: 'intermediate',
    difficultyPct: 48,
    lang: 'ts',
    comments: 2,
    age: '4 days',
    assignees: 1,
    estTime: '3–5 hours',
    githubUrl: 'https://github.com/supabase/supabase/issues',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 4,
    repo: 'tailwindlabs/tailwindcss',
    repoStars: '80.1k',
    repoStarsNum: 80100,
    av: 'TW',
    avColor: 'blue',
    title: 'Improve JIT warning message for unknown utility classes',
    desc: "When users type a class that doesn't exist, the current warning is terse. Add the closest matching class as a suggestion to help developers debug faster.",
    tags: [
      { label: 'Beginner', type: 'difficulty' },
      { label: 'JavaScript', type: 'lang' },
      { label: 'DX', type: 'topic' },
      { label: 'good-first-issue', type: 'topic' },
    ],
    difficulty: 'beginner',
    difficultyPct: 28,
    lang: 'js',
    comments: 11,
    age: '6 hours',
    assignees: 0,
    estTime: '2–4 hours',
    githubUrl: 'https://github.com/tailwindlabs/tailwindcss/issues',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 5,
    repo: 'rust-lang/rustfmt',
    repoStars: '5.8k',
    repoStarsNum: 5800,
    av: 'RS',
    avColor: 'red',
    title: 'Add rustfmt support for formatting let-else chains',
    desc: "The let-else syntax introduced in Rust 1.65 isn't formatted consistently when chained. Implement the formatting rule following RFC 3137.",
    tags: [
      { label: 'Advanced', type: 'difficulty' },
      { label: 'Rust', type: 'lang' },
      { label: 'Feature', type: 'topic' },
    ],
    difficulty: 'advanced',
    difficultyPct: 78,
    lang: 'rust',
    comments: 14,
    age: '3 days',
    assignees: 0,
    estTime: '1–2 days',
    githubUrl: 'https://github.com/rust-lang/rustfmt/issues',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 6,
    repo: 'prisma/prisma',
    repoStars: '37.9k',
    repoStarsNum: 37900,
    av: 'PR',
    avColor: 'blue',
    title: 'Add JSDoc comments to generated client types',
    desc: 'The Prisma Client auto-generated types are missing JSDoc comments. Schema field descriptions should be carried through to improve IDE experience for all users.',
    tags: [
      { label: 'Intermediate', type: 'difficulty' },
      { label: 'TypeScript', type: 'lang' },
      { label: 'Documentation', type: 'topic' },
      { label: 'help-wanted', type: 'topic' },
    ],
    difficulty: 'intermediate',
    difficultyPct: 55,
    lang: 'ts',
    comments: 22,
    age: '5 days',
    assignees: 0,
    estTime: '4–8 hours',
    githubUrl: 'https://github.com/prisma/prisma/issues',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 7,
    repo: 'tiangolo/sqlmodel',
    repoStars: '14.2k',
    repoStarsNum: 14200,
    av: 'SM',
    avColor: 'amber',
    title: 'Fix incorrect pagination count when using .offset() with relationships',
    desc: 'When a query uses .offset() alongside relationship loading, the total count returned by select() is incorrect. Reproducible with Team → Member relationship test case.',
    tags: [
      { label: 'Intermediate', type: 'difficulty' },
      { label: 'Python', type: 'lang' },
      { label: 'Bug Fix', type: 'topic' },
    ],
    difficulty: 'intermediate',
    difficultyPct: 42,
    lang: 'python',
    comments: 8,
    age: '1 day',
    assignees: 0,
    estTime: '3–6 hours',
    githubUrl: 'https://github.com/tiangolo/sqlmodel/issues',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 8,
    repo: 'grafana/grafana',
    repoStars: '60.4k',
    repoStarsNum: 60400,
    av: 'GF',
    avColor: 'red',
    title: 'Accessibility: add keyboard navigation to time range picker',
    desc: 'The time range picker in the dashboard toolbar is not fully keyboard navigable. Implement focus trap and arrow key navigation per ARIA combobox pattern.',
    tags: [
      { label: 'Intermediate', type: 'difficulty' },
      { label: 'TypeScript', type: 'lang' },
      { label: 'Accessibility', type: 'topic' },
      { label: 'good-first-issue', type: 'topic' },
    ],
    difficulty: 'intermediate',
    difficultyPct: 50,
    lang: 'ts',
    comments: 6,
    age: '8 days',
    assignees: 0,
    estTime: '4–6 hours',
    githubUrl: 'https://github.com/grafana/grafana/issues',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 9,
    repo: 'golang/go',
    repoStars: '122k',
    repoStarsNum: 122000,
    av: 'GO',
    avColor: 'blue',
    title: 'Improve error message for nil map assignment',
    desc: "When users try to assign to a nil map, the runtime panic message doesn't indicate which map variable caused the panic. Improve the message to include context.",
    tags: [
      { label: 'Beginner', type: 'difficulty' },
      { label: 'Go', type: 'lang' },
      { label: 'Bug Fix', type: 'topic' },
    ],
    difficulty: 'beginner',
    difficultyPct: 30,
    lang: 'go',
    comments: 3,
    age: '12 days',
    assignees: 0,
    estTime: '2–4 hours',
    githubUrl: 'https://github.com/golang/go/issues',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    id: 10,
    repo: 'django/django',
    repoStars: '78.3k',
    repoStarsNum: 78300,
    av: 'DJ',
    avColor: 'green',
    title: 'Add deprecation warning for string-based view names in URL patterns',
    desc: "String-based view names have been soft-deprecated but there's no runtime warning. Add a DeprecationWarning to guide users toward callable views.",
    tags: [
      { label: 'Beginner', type: 'difficulty' },
      { label: 'Python', type: 'lang' },
      { label: 'Deprecation', type: 'topic' },
    ],
    difficulty: 'beginner',
    difficultyPct: 25,
    lang: 'python',
    comments: 5,
    age: '2 days',
    assignees: 0,
    estTime: '1–3 hours',
    githubUrl: 'https://github.com/django/django/issues',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];

export const PRIYA_PORTFOLIO: PortfolioProfile = {
  name: 'Priya Sharma',
  handle: '@priya',
  title: 'Frontend Engineer open to opportunities',
  bio: 'Self-taught dev passionate about open source. Contributing to TypeScript and React ecosystem projects since 2023. Based in Bangalore, India. Looking for my first junior engineering role.',
  location: 'Bangalore, India',
  website: 'priyasharma.dev',
  email: 'priya@priyasharma.dev',
  contributingSince: 'Jan 2023',
  avatarInitials: 'PS',
  isPro: true,
  stats: {
    mergedPRs: 14,
    repositories: 6,
    combinedStars: '220k+',
    linesContributed: '+1,847',
    impactScore: 92,
    streakMonths: 14,
  },
  skills: [
    { name: 'TypeScript', pct: 82, color: '#1A4AC4', dot: '#3178C6' },
    { name: 'React', pct: 74, color: '#1A7A4A', dot: '#61DAFB' },
    { name: 'Next.js', pct: 60, color: '#3D3A34', dot: '#000000' },
    { name: 'JavaScript', pct: 48, color: '#C47A1A', dot: '#F7DF1E' },
    { name: 'Tailwind CSS', pct: 40, color: '#1A7A4A', dot: '#06B6D4' },
    { name: 'Testing (Vitest)', pct: 35, color: '#6B1AC4', dot: '#6E9F18' },
  ],
  pullRequests: [
    {
      repo: 'vercel/next.js',
      stars: '119k',
      av: 'NX',
      avColor: 'dark',
      title: 'Fix misleading error message when API route handler returns undefined',
      desc: 'Improved the runtime error to suggest the user return a `Response` object, with a code example. Reduced confusion for 100k+ developers hitting this edge case.',
      tags: [
        { label: 'TypeScript', type: 'lang' },
        { label: 'Bug Fix', type: 'topic' },
        { label: 'DX Improvement', type: 'topic' },
      ],
      status: 'merged',
      additions: '+47',
      deletions: '-3',
      files: 2,
      reviews: 3,
      date: 'Dec 2023',
      impact: '↑ High impact',
      githubUrl: 'https://github.com/vercel/next.js',
    },
    {
      repo: 'tailwindlabs/tailwindcss',
      stars: '80.1k',
      av: 'TW',
      avColor: 'blue',
      title: 'Add closest-match suggestion to unknown utility class warning',
      desc: 'When JIT encounters an unknown class, it now suggests the closest valid class using Levenshtein distance. Helps beginners spot typos instantly.',
      tags: [
        { label: 'JavaScript', type: 'lang' },
        { label: 'Feature', type: 'topic' },
        { label: 'DX', type: 'topic' },
      ],
      status: 'merged',
      additions: '+89',
      deletions: '-12',
      files: 3,
      reviews: 5,
      date: 'Nov 2023',
      impact: '↑ High impact',
      githubUrl: 'https://github.com/tailwindlabs/tailwindcss',
    },
    {
      repo: 'supabase/supabase',
      stars: '61.2k',
      av: 'SB',
      avColor: 'green',
      title: 'Add comprehensive unit tests for storage bucket validation',
      desc: 'Added 24 unit tests using Vitest for the bucket name validation logic, covering edge cases including unicode, length limits, and special character restrictions.',
      tags: [
        { label: 'TypeScript', type: 'lang' },
        { label: 'Testing', type: 'topic' },
      ],
      status: 'merged',
      additions: '+312',
      deletions: '-8',
      files: 2,
      reviews: 2,
      date: 'Oct 2023',
      impact: '↑ Medium impact',
      githubUrl: 'https://github.com/supabase/supabase',
    },
    {
      repo: 'facebook/react',
      stars: '224k',
      av: 'RE',
      avColor: 'blue',
      title: 'Add JSDoc documentation to useCallback and useMemo hooks',
      desc: "Added comprehensive JSDoc comments with parameter descriptions, return types, and usage examples for two of React's most commonly misunderstood hooks.",
      tags: [
        { label: 'TypeScript', type: 'lang' },
        { label: 'Documentation', type: 'topic' },
      ],
      status: 'merged',
      additions: '+68',
      deletions: '-0',
      files: 1,
      reviews: 4,
      date: 'Sep 2023',
      impact: '↑ High impact',
      githubUrl: 'https://github.com/facebook/react',
    },
    {
      repo: 'prisma/prisma',
      stars: '37.9k',
      av: 'PR',
      avColor: 'purple',
      title: 'Carry through Prisma schema field descriptions to generated client JSDoc',
      desc: 'Schema comments annotated with `///` are now surfaced as JSDoc in the generated Prisma Client, giving developers inline documentation in their IDE.',
      tags: [
        { label: 'TypeScript', type: 'lang' },
        { label: 'Feature', type: 'topic' },
        { label: 'DX', type: 'topic' },
      ],
      status: 'merged',
      additions: '+203',
      deletions: '-14',
      files: 6,
      reviews: 7,
      date: 'Aug 2023',
      impact: '↑ High impact',
      githubUrl: 'https://github.com/prisma/prisma',
    },
    {
      repo: 'grafana/grafana',
      stars: '60.4k',
      av: 'GF',
      avColor: 'red',
      title: 'Implement keyboard navigation for time range picker (ARIA combobox)',
      desc: 'Made the dashboard time range picker fully keyboard navigable per WCAG 2.1 AA. Added focus trap, arrow key navigation, and Escape to close.',
      tags: [
        { label: 'TypeScript', type: 'lang' },
        { label: 'Accessibility', type: 'topic' },
      ],
      status: 'merged',
      additions: '+156',
      deletions: '-28',
      files: 4,
      reviews: 6,
      date: 'Jul 2023',
      impact: '↑ High impact',
      githubUrl: 'https://github.com/grafana/grafana',
    },
  ],
  timeline: [
    {
      date: 'Feb 2025',
      title: 'Reached 14 merged PRs',
      repo: 'Multiple repos',
      desc: 'Hit milestone of 14 merged pull requests across 6 major open source projects.',
    },
    {
      date: 'Dec 2023',
      title: 'First contribution to Next.js',
      repo: 'vercel/next.js (★119k)',
      desc: 'Fixed a confusing error message in the API routes handler. PR merged in 3 days.',
    },
    {
      date: 'Oct 2023',
      title: 'Added 24 unit tests to Supabase',
      repo: 'supabase/supabase (★61k)',
      desc: 'Largest contribution to date: 312 lines of tests covering the storage SDK.',
    },
    {
      date: 'Sep 2023',
      title: 'JSDoc for React hooks',
      repo: 'facebook/react (★224k)',
      desc: 'First contribution to React itself. Added documentation for useCallback + useMemo.',
    },
    {
      date: 'May 2023',
      title: 'Joined FirstIssue Pro',
      repo: 'firstissue.xyz',
      desc: 'Started using FirstIssue to find quality issues and track OSS progress.',
    },
    {
      date: 'Jan 2023',
      title: 'First ever OSS contribution',
      repo: 'tailwindlabs/tailwindcss',
      desc: 'Fixed a one-line typo in the documentation. Took 3 weeks to summon the courage to submit.',
    },
  ],
  repos: [
    { av: 'RE', avColor: 'blue', name: 'facebook/react', meta: '★ 224k · TypeScript', prs: '3 PRs' },
    { av: 'NX', avColor: 'dark', name: 'vercel/next.js', meta: '★ 119k · TypeScript', prs: '2 PRs' },
    { av: 'TW', avColor: 'blue', name: 'tailwindlabs/tailwindcss', meta: '★ 80k · JavaScript', prs: '3 PRs' },
    { av: 'GF', avColor: 'red', name: 'grafana/grafana', meta: '★ 60k · TypeScript', prs: '2 PRs' },
    { av: 'SB', avColor: 'green', name: 'supabase/supabase', meta: '★ 61k · TypeScript', prs: '2 PRs' },
    { av: 'PR', avColor: 'purple', name: 'prisma/prisma', meta: '★ 38k · TypeScript', prs: '2 PRs' },
  ],
  tags: [
    { label: 'TypeScript', size: 1 },
    { label: 'React', size: 1 },
    { label: 'Next.js', size: 2 },
    { label: 'Testing', size: 2 },
    { label: 'Tailwind CSS', size: 3 },
    { label: 'Accessibility', size: 3 },
    { label: 'Documentation', size: 3 },
    { label: 'Node.js', size: 4 },
    { label: 'Bug Fix', size: 4 },
    { label: 'Performance', size: 4 },
    { label: 'DX', size: 4 },
  ],
};

export const TICKER_ITEMS = [
  'react/react — add JSDoc to hooks',
  'vercel/next.js — fix typo in docs',
  'fastapi/fastapi — add type hints',
  'supabase/supabase — write unit test',
  'tailwindlabs/tailwindcss — improve error message',
  'django/django — update deprecation warning',
  'golang/go — fix example code in docs',
  'rust-lang/rust — improve compiler hint',
  'prisma/prisma — add JSDoc to client',
  'grafana/grafana — keyboard navigation fix',
  'sveltejs/svelte — fix TS types',
  'vitejs/vite — improve HMR error messages',
];
